import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function About() {
    return (
      <div className={styles.container}>
        <Head>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            About the BCOF
          </h1>

          <h2>
            <Link href="/">Back to Home</Link>
          </h2>

        </main>
      </div>

    )
  }