import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BCOF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the BCOF Landing Page! Site is under construction...
        </h1>

        <h2 className={styles.title}>
          <Link href="/about">About Us</Link>
        </h2>
      </main>

    </div>
  )
}
